//auth reducers
export const LOADING_UI = "LOADING_UI";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SERVER_ERROR = "SERVER_ERROR";
export const SET_ERROR = "SET_ERROR";
export const SET_USER = "SET_USER";
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";

//dashboard reducers
export const LOAD_DASHBOARD = "LOAD_DASHBOARD";
export const SET_DASHBOARD_DATA = "SET_DASHBOARD_DATA";

//vendor reducers
export const LOADING_VENDOR_LIST = "LOADING_VENDOR_LIST";
export const SET_VENDORS_LIST = "SET_VENDOR_LIST";
export const SET_VENDOR_ERROR = "SET_VENDOR_LIST_ERROR";
export const CLEAR_VENDOR_LIST_ERROR = "CLEAR_VENDOR_LIST_ERROR";
export const DELETE_VENDOR = "DELETE_VENDOR";
export const SET_VENDOR_PROFILE = "SET_VENDOR_PROFILE";
export const SET_VENDOR_PRODUCTS = "SET_VENDOR_PRODUCTS";
export const UPDATE_VENDOR_STATUS = "UPDATE_VENDOR_STATUS";
export const DELETE_VENDOR_PRODUCT = "DELETE_VENDOR_PRODUCT";

//customer reducers
export const CUSTOMER_LODING = "CUSTOMER_LODING";
export const SET_CUSTOMER_LIST = "SET_CUSTOMER_LIST";
export const CUSTOMER_PROFILE = "CUSTOMER_PROFILE";
export const CUSTOMER_ORDERS = "CUSTOMER_ORDERS";
export const SET_CUSTOMER_ERROR = "SET_CUSTOMER_ERROR";
export const CLEAR_CUSTOMER_ERROR = "CLEAR_CUSTOMER_ERROR";

// category reducers
export const LOADING_CATEGORIES = "LOADING_CATEGORIES";
export const GET_CATEGORIES_LIST = "GET_CATEGORIES_LIST";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const SET_CATEGORY_VISIBILITY = "SET_CATEGORY_VISIBILITY";
export const SET_CATEGORIES_ERROR = "SET_CATEGORIES_ERROR";
export const CLEAR_CATEGORIES_ERROR = "CLEAR_CATEGORIES_ERROR";

// group reducers
export const LOADING_GROUPS = "LOADING_GROUPS";
export const GET_GROUP_LIST = "GET_GROUP_LIST";
export const DELETE_GROUP = "DELETE_GROUP";
export const SET_GROUP_VISIBILITY = "SET_GROUP_VISIBILITY";
export const SET_GROUPS_ERROR = "SET_GROUPS_ERROR";
export const CLEAR_GROUPS_ERROR = "CLEAR_GROUPS_ERROR";

// products reducers
export const LOADING_PRODUCTS = "LOADING_PRODUCTS";
export const PRODUCTS_LIST = "PRODUCTS_LIST";
export const PRODUCTS_ERROR = "PRODUCTS_ERROR";
export const CLERAR_PRODUCTS_ERROR = "CLERAR_PRODUCTS_ERROR";
export const PRODUCTS_DELETE_ERROR = "PRODUCTS_DELETE_ERROR";
export const PRODUCTS_DELETED = "PRODUCTS_DELETED";
export const PRODUCTS_DELETE_CALL = "PRODUCTS_DELETE_CALL";

/* banners reducers */
export const LOADING_BANNERS = "LOADING_BANNERS";
export const FETCH_BANNERS_LIST = "FETCH_BANNERS_LIST";
export const DELETE_BANNER = "DELETE_BANNER";
export const FETCH_BANNER_IMAGES = "FETCH_BANNER_IMAGES";
export const ACTIVE_BANNER_IMAGE = "ACTIVE_BANNER_IMAGE";
export const DELETE_BANNER_IMAGE = "DELETE_BANNER_IMAGE";
export const BANNERS_ERROR = "BANNERS_ERROR";
export const CLEAR_BANNER_ERROR = "CLEAR_BANNER_ERROR";

/* Transactions reducers */
export const LOADING_TRANSACTIONS = "LOADING_TRANSACTIONS";
export const TRANSACTIONS_LIST = "TRANSACTIONS_LIST";

/* snackbar reducers */
export const SET_SNACKBAR = "SET_SNACKBAR";
export const SNACKBAR_CLEAR = "SNACKBAR_CLEAR";

/* order action types */
export const ORDER_LOADING = "ORDER_LOADING";
export const ORDER_LOADED = "ORDER_LOADED";
export const ORDER_LOADING_ERROR = "ORDER_LOADING_ERROR";



// catalog reducers
export const LOADING_CATALOGS = "LOADING_CATALOGS";
export const GET_CATALOG_LIST = "GET_CATALOG_LIST";
export const EDIT_CATALOG = "EDIT_CATALOG";
export const SET_CATALOG_VISIBILITY = "SET_CATALOG_VISIBILITY";
export const SET_CATALOG_ERROR = "SET_CATALOG_ERROR";
export const CLEAR_CATALOG_ERROR = "CLEAR_CATALOG_ERROR";
export const SET_PRODUCTS_LIST_FETCHED = "SET_PRODUCTS_LIST_FETCHED";
export const SET_SELECTED_PRODUCTS_LIST = "SET_SELECTED_PRODUCTS_LIST";
export const SET_UNSELECTED_PRODUCT_LIST =  "SET_UNSELECTED_PRODUCT_LIST";
export const ERROR_LOADING_PRODUCTS_FOR_CATEGORY = "ERROR_LOADING_PRODUCTS_FOR_CATEGORY";
export const EDIT_CATALOG_DATA_SET = 'EDIT_CATALOG_DATA_SET';
export const SET_CATEGORY_ID = "SET_CATEGORY_ID";